<?php

return [
    'categories' => [
        [
            'key' => 'people',
            'label' => 'People',
            'icon' => '👤',
            'objects' => [
                ['value' => 'person', 'label' => 'Person'],
                ['value' => 'face', 'label' => 'Face'],
                ['value' => 'head', 'label' => 'Head'],
                ['value' => 'hand', 'label' => 'Hand'],
                ['value' => 'human_body', 'label' => 'Human Body'],
            ],
        ],
        [
            'key' => 'vehicles',
            'label' => 'Vehicles',
            'icon' => '🚗',
            'objects' => [
                ['value' => 'car', 'label' => 'Car'],
                ['value' => 'truck', 'label' => 'Truck'],
                ['value' => 'bus', 'label' => 'Bus'],
                ['value' => 'motorcycle', 'label' => 'Motorcycle'],
                ['value' => 'bicycle', 'label' => 'Bicycle'],
                ['value' => 'van', 'label' => 'Van'],
                ['value' => 'taxi', 'label' => 'Taxi'],
                ['value' => 'ambulance', 'label' => 'Ambulance'],
                ['value' => 'fire_truck', 'label' => 'Fire Truck'],
                ['value' => 'police_car', 'label' => 'Police Car'],
                ['value' => 'boat', 'label' => 'Boat'],
                ['value' => 'airplane', 'label' => 'Airplane'],
                ['value' => 'train', 'label' => 'Train'],
            ],
        ],
        [
            'key' => 'animals',
            'label' => 'Animals',
            'icon' => '🐕',
            'objects' => [
                ['value' => 'dog', 'label' => 'Dog'],
                ['value' => 'cat', 'label' => 'Cat'],
                ['value' => 'bird', 'label' => 'Bird'],
                ['value' => 'horse', 'label' => 'Horse'],
                ['value' => 'cow', 'label' => 'Cow'],
                ['value' => 'sheep', 'label' => 'Sheep'],
                ['value' => 'goat', 'label' => 'Goat'],
                ['value' => 'pig', 'label' => 'Pig'],
                ['value' => 'chicken', 'label' => 'Chicken'],
                ['value' => 'fish', 'label' => 'Fish'],
            ],
        ],
        [
            'key' => 'household_furniture',
            'label' => 'Household / Furniture',
            'icon' => '🏠',
            'objects' => [
                ['value' => 'chair', 'label' => 'Chair'],
                ['value' => 'couch', 'label' => 'Couch'],
                ['value' => 'table', 'label' => 'Table'],
                ['value' => 'bed', 'label' => 'Bed'],
                ['value' => 'desk', 'label' => 'Desk'],
                ['value' => 'cabinet', 'label' => 'Cabinet'],
                ['value' => 'door', 'label' => 'Door'],
                ['value' => 'window', 'label' => 'Window'],
                ['value' => 'lamp', 'label' => 'Lamp'],
                ['value' => 'mirror', 'label' => 'Mirror'],
                ['value' => 'television', 'label' => 'Television'],
                ['value' => 'refrigerator', 'label' => 'Refrigerator'],
                ['value' => 'microwave', 'label' => 'Microwave'],
                ['value' => 'oven', 'label' => 'Oven'],
            ],
        ],
        [
            'key' => 'electronics',
            'label' => 'Electronics',
            'icon' => '💻',
            'objects' => [
                ['value' => 'laptop', 'label' => 'Laptop'],
                ['value' => 'computer', 'label' => 'Computer'],
                ['value' => 'mobile_phone', 'label' => 'Mobile Phone'],
                ['value' => 'tablet', 'label' => 'Tablet'],
                ['value' => 'keyboard', 'label' => 'Keyboard'],
                ['value' => 'mouse', 'label' => 'Mouse'],
                ['value' => 'camera', 'label' => 'Camera'],
                ['value' => 'headphones', 'label' => 'Headphones'],
                ['value' => 'remote_control', 'label' => 'Remote Control'],
            ],
        ],
        [
            'key' => 'personal_items',
            'label' => 'Personal Items',
            'icon' => '🎒',
            'objects' => [
                ['value' => 'backpack', 'label' => 'Backpack'],
                ['value' => 'handbag', 'label' => 'Handbag'],
                ['value' => 'suitcase', 'label' => 'Suitcase'],
                ['value' => 'wallet', 'label' => 'Wallet'],
                ['value' => 'umbrella', 'label' => 'Umbrella'],
                ['value' => 'hat', 'label' => 'Hat'],
                ['value' => 'glasses', 'label' => 'Glasses'],
                ['value' => 'shoes', 'label' => 'Shoes'],
                ['value' => 'clothing', 'label' => 'Clothing'],
            ],
        ],
        [
            'key' => 'food_drink',
            'label' => 'Food & Drink',
            'icon' => '🍔',
            'objects' => [
                ['value' => 'bottle', 'label' => 'Bottle'],
                ['value' => 'cup', 'label' => 'Cup'],
                ['value' => 'mug', 'label' => 'Mug'],
                ['value' => 'plate', 'label' => 'Plate'],
                ['value' => 'bowl', 'label' => 'Bowl'],
                ['value' => 'fork', 'label' => 'Fork'],
                ['value' => 'knife', 'label' => 'Knife'],
                ['value' => 'spoon', 'label' => 'Spoon'],
                ['value' => 'food', 'label' => 'Food'],
                ['value' => 'fruit', 'label' => 'Fruit'],
                ['value' => 'pizza', 'label' => 'Pizza'],
                ['value' => 'hamburger', 'label' => 'Hamburger'],
                ['value' => 'sandwich', 'label' => 'Sandwich'],
            ],
        ],
        [
            'key' => 'tools_objects',
            'label' => 'Tools / Objects',
            'icon' => '🛠️',
            'objects' => [
                ['value' => 'scissors', 'label' => 'Scissors'],
                ['value' => 'hammer', 'label' => 'Hammer'],
                ['value' => 'screwdriver', 'label' => 'Screwdriver'],
                ['value' => 'drill', 'label' => 'Drill'],
                ['value' => 'tool', 'label' => 'Tool'],
                ['value' => 'box', 'label' => 'Box'],
                ['value' => 'package', 'label' => 'Package'],
                ['value' => 'book', 'label' => 'Book'],
                ['value' => 'paper', 'label' => 'Paper'],
                ['value' => 'pen', 'label' => 'Pen'],
                ['value' => 'pencil', 'label' => 'Pencil'],
                ['value' => 'ball', 'label' => 'Ball'],
                ['value' => 'toy', 'label' => 'Toy'],
            ],
        ],
        [
            'key' => 'security_relevant',
            'label' => 'Security-relevant',
            'icon' => '🔐',
            'objects' => [
                ['value' => 'knife', 'label' => 'Knife'],
                ['value' => 'gun_firearm', 'label' => 'Gun / Firearm'],
                ['value' => 'weapon', 'label' => 'Weapon'],
                ['value' => 'helmet', 'label' => 'Helmet'],
                ['value' => 'mask', 'label' => 'Mask'],
                ['value' => 'license_plate', 'label' => 'License Plate'],
                ['value' => 'security_camera', 'label' => 'Security Camera'],
                ['value' => 'traffic_light', 'label' => 'Traffic Light'],
                ['value' => 'stop_sign', 'label' => 'Stop Sign'],
            ],
        ],
    ],
];
