<?php

namespace App\Ai\Agents;

use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Ai\Attributes\Model;
use Laravel\Ai\Attributes\Provider;
use Laravel\Ai\Contracts\Agent;
use Laravel\Ai\Contracts\HasStructuredOutput;
use Laravel\Ai\Enums\Lab;
use Laravel\Ai\Promptable;
use Stringable;

#[Provider(Lab::Gemini)]
#[Model('gemini-3.6-flash')]
class ContentModerationAgent implements Agent, HasStructuredOutput
{
    use Promptable;

    /**
     * Get the instructions that the agent should follow.
     */
    public function instructions(): Stringable|string
    {
        return <<<'INSTRUCTIONS'
            You are a video content moderation analyst. You will be given content
            moderation detections generated by a computer-vision system for a single
            video — labels, their occurrence counts, average/min/max confidence, and
            individual detection timestamps (in seconds from the start of the video).
            You have not seen the video itself and are not given its title or
            filename — base everything strictly on this detected data.

            Instructions:
            1. Review the detected moderation labels, confidence scores, and
               timestamps.
            2. Determine whether the video contains potentially unsafe, explicit,
               violent, disturbing, or otherwise inappropriate content based only on
               the provided detections.
            3. Consider the confidence of the detections and their timestamps when
               assessing the overall result.
            4. Do not assume content that is not represented in the detections.
            5. If the evidence is weak or ambiguous, clearly indicate that.
            6. Determine an overall moderation status: SAFE, REVIEW, or UNSAFE.
            7. Assign a severity level: NONE, LOW, MEDIUM, or HIGH.
            8. Provide a confidence score from 0 to 100 representing your confidence
               in the overall assessment.
            9. Identify the most relevant timestamp when applicable; if none is
               applicable (e.g. the video is clearly safe), leave it null.
            10. Provide a short, factual explanation of the assessment.
            11. Do not provide unnecessary graphic or explicit descriptions.
            INSTRUCTIONS;
    }

    /**
     * Get the agent's structured output schema definition.
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'status' => $schema->string()
                ->enum(['SAFE', 'REVIEW', 'UNSAFE'])
                ->required(),
            'severity' => $schema->string()
                ->enum(['NONE', 'LOW', 'MEDIUM', 'HIGH'])
                ->required(),
            'confidence' => $schema->integer()
                ->min(0)->max(100)
                ->description('Confidence in this assessment, 0-100.')
                ->required(),
            'timestamp' => $schema->number()
                ->nullable()
                ->description('The most relevant timestamp, in seconds, when applicable.')
                ->required(),
            'summary' => $schema->string()
                ->description('A one-sentence, plain-language summary of the assessment.')
                ->required(),
            'reasoning' => $schema->string()
                ->description('A short, factual explanation of the assessment, without unnecessary graphic detail.')
                ->required(),
        ];
    }
}
