<?php

namespace App\Ai\Agents;

use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Ai\Attributes\Model;
use Laravel\Ai\Attributes\Provider;
use Laravel\Ai\Attributes\Timeout;
use Laravel\Ai\Contracts\Agent;
use Laravel\Ai\Contracts\HasStructuredOutput;
use Laravel\Ai\Enums\Lab;
use Laravel\Ai\Promptable;
use Stringable;

#[Provider(Lab::Gemini)]
#[Model('gemini-3.6-flash')]
#[Timeout(120)]
class ObjectDetectionAgent implements Agent, HasStructuredOutput
{
    use Promptable;

    /**
     * Get the instructions that the agent should follow.
     */
    public function instructions(): Stringable|string
    {
        return <<<'INSTRUCTIONS'
            You are a video intelligence analyst. You will be given object detections
            generated by a computer-vision system for a single video — labels, their
            occurrence counts, average/min/max confidence, and individual detection
            timestamps (in seconds from the start of the video). You have not seen
            the video itself and are not given its title or filename — base
            everything strictly on this detected data.

            Instructions:
            1. Analyze the detected objects, confidence scores, and timestamps.
            2. Identify the most relevant objects present in the video.
            3. Group repeated detections of the same object when appropriate.
            4. Consider the timestamps to understand when objects appear or
               disappear.
            5. Do not assume an object is present if it was not detected.
            6. Do not infer actions, relationships, or events that are not supported
               by the detections.
            7. Highlight notable objects, unusual combinations, or significant
               changes in the detected objects over time.
            8. If the detections are insufficient to determine something, explicitly
               say so.
            9. Provide a concise summary of what was detected.
            10. Assign an overall confidence score from 0 to 100 representing your
                confidence in the summary.
            11. Identify the most relevant timestamp when applicable; if none is
                applicable, leave it null.
            INSTRUCTIONS;
    }

    /**
     * Get the agent's structured output schema definition.
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'summary' => $schema->string()
                ->description('A concise summary of what was detected.')
                ->required(),
            'confidence' => $schema->integer()
                ->min(0)->max(100)
                ->description('Confidence in this summary, 0-100.')
                ->required(),
            'timestamp' => $schema->number()
                ->nullable()
                ->description('The most relevant timestamp, in seconds, when applicable.')
                ->required(),
            'objects' => $schema->array()
                ->items($schema->object(fn (JsonSchema $schema) => [
                    'label' => $schema->string()->required(),
                    'count' => $schema->integer()->required(),
                ]))
                ->description('The most relevant objects detected, with repeated detections grouped.')
                ->required(),
            'notable_observations' => $schema->array()
                ->items($schema->string())
                ->description('Notable objects, unusual combinations, or significant changes over time. Empty if none.')
                ->required(),
        ];
    }
}
